# Generated by Django 4.0.4 on 2022-04-11 19:09

import django.core.validators
from django.db import migrations, models
import zezere.models


class Migration(migrations.Migration):

    dependencies = [
        ('zezere', '0012_auto_20200323_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RunRequest notes'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^([0-9A-F]{2}[:]){5}([0-9A-F]{2})$'), zezere.models.validator_disallow_blacklisted_mac], verbose_name='Device MAC Address'),
        ),
    ]
